@echo off
setlocal
chcp 65001 >nul
title [1H-PAPER]
echo [1H-PAPER]
echo.
cd /d %~dp0
set ORDER_15M_PAPER_VARIANT_ID=1h-paper
set ORDER_15M_PAPER_OUTPUT_DIR=paper-1h
set ORDER_15M_PAPER_LOG_PREFIX=1H paper
set ORDER_15M_PAPER_WINDOW_MINUTES=60
set ORDER_15M_PAPER_WINDOW_LABEL=1H
set ORDER_15M_PAPER_EVENT_PREFIX=bitcoin-up-or-down-
set ORDER_15M_PAPER_EVENT_SUFFIX=-et
set ORDER_15M_PAPER_SLUG_MODE=calendar-et
set ORDER_15M_PAPER_REFERENCE_LOOKBACK_WINDOWS=2
set ORDER_15M_PAPER_FIRST_ENTRY_DEADLINE_MINUTES=30
set ORDER_15M_PAPER_SAMPLE_INTERVAL_MS=5000
set ORDER_15M_PAPER_STRATEGIES=38/38,adaptive2
python -u scripts\order_15m_paper.py
pause
