const ALL_WEATHER_CITY_CONFIGS = [
  {
    citySlug: "beijing",
    cityZh: "北京",
    cityEn: "Beijing",
    region: "domestic",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-beijing",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-beijing-on-april-16-2026",
    settlementStationName: "Beijing Capital International Airport",
    settlementStationCode: "ZBAA",
    forecastTarget: "北京顺义区",
    forecastBackupTarget: "北京朝阳区",
    nmcStationCode: "MKoqG",
    nmcStationId: "54398",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/ABJ/shunyi.html",
    note: "按顺义页抓取，朝阳仅作辅助对照。",
  },
  {
    citySlug: "shanghai",
    cityZh: "上海",
    cityEn: "Shanghai",
    region: "domestic",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-shanghai",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-shanghai-on-april-16-2026",
    settlementStationName: "Shanghai Pudong International Airport",
    settlementStationCode: "ZSPD",
    forecastTarget: "上海浦东新区",
    forecastBackupTarget: null,
    nmcStationCode: "atcMf",
    nmcStationId: "58370",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/ASH/pudong.html",
    note: "直接按浦东页抓取。",
  },
  {
    citySlug: "guangzhou",
    cityZh: "广州",
    cityEn: "Guangzhou",
    region: "domestic",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-guangzhou",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-guangzhou-on-april-16-2026",
    settlementStationName: "Guangzhou Baiyun International Airport",
    settlementStationCode: "ZGGG",
    forecastTarget: "广州花都区",
    forecastBackupTarget: "广州白云区",
    nmcStationCode: "DFILe",
    nmcStationId: "59284",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/AGD/huadu.html",
    note: "白云机场优先按花都页抓取。",
  },
  {
    citySlug: "shenzhen",
    cityZh: "深圳",
    cityEn: "Shenzhen",
    region: "domestic",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-shenzhen",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-shenzhen-on-april-16-2026",
    settlementStationName: "Shenzhen Bao'an International Airport",
    settlementStationCode: "ZGSZ",
    forecastTarget: "深圳市",
    forecastBackupTarget: "深圳宝安区",
    nmcStationCode: "AhpEU",
    nmcStationId: "59493",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/AGD/shenzuo.html",
    note: "中央台当前没有单独宝安页，先用深圳城市页。",
  },
  {
    citySlug: "wuhan",
    cityZh: "武汉",
    cityEn: "Wuhan",
    region: "domestic",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-wuhan",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-wuhan-on-april-16-2026",
    settlementStationName: "Wuhan Tianhe International Airport",
    settlementStationCode: "ZHHH",
    forecastTarget: "武汉市",
    forecastBackupTarget: "武汉黄陂区",
    nmcStationCode: "bSpCz",
    nmcStationId: "57494",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/AHB/wuhan.html",
    note: "中央台当前没有黄陂独立页，先用武汉城市页。",
  },
  {
    citySlug: "chengdu",
    cityZh: "成都",
    cityEn: "Chengdu",
    region: "domestic",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-chengdu",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-chengdu-on-april-16-2026",
    settlementStationName: "Chengdu Shuangliu International Airport",
    settlementStationCode: "ZUUU",
    forecastTarget: "成都双流区",
    forecastBackupTarget: null,
    nmcStationCode: "grFhZ",
    nmcStationId: "56288",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/ASC/shuangliu.html",
    note: "直接按双流页抓取。",
  },
  {
    citySlug: "chongqing",
    cityZh: "重庆",
    cityEn: "Chongqing",
    region: "domestic",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-chongqing",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-chongqing-on-april-16-2026",
    settlementStationName: "Chongqing Jiangbei International Airport",
    settlementStationCode: "ZUCK",
    forecastTarget: "重庆渝北区",
    forecastBackupTarget: null,
    nmcStationCode: "xFVYU",
    nmcStationId: "57513",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/ACQ/yubei.html",
    note: "直接按渝北页抓取。",
  },
  {
    citySlug: "hong-kong",
    cityZh: "香港",
    cityEn: "Hong Kong",
    region: "domestic",
    forecastSource: "hko-fnd",
    eventBaseSlug: "highest-temperature-in-hong-kong",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-hong-kong-on-april-16-2026",
    settlementStationName: "Hong Kong Observatory",
    settlementStationCode: null,
    forecastTarget: "香港天文台",
    forecastBackupTarget: "香港",
    nmcStationCode: "hcBhy",
    nmcStationId: "45005",
    nmcPageUrl: "https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=fnd&lang=en",
    note: "改用香港天文台官方 9-day forecast open data。",
  },
  {
    citySlug: "taipei",
    cityZh: "台北",
    cityEn: "Taipei",
    region: "domestic",
    forecastSource: "cwa-county-63",
    eventBaseSlug: "highest-temperature-in-taipei",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-taipei-on-april-16-2026",
    settlementStationName: "Taipei Songshan Airport Station",
    settlementStationCode: "RCSS",
    forecastTarget: "台北市",
    forecastBackupTarget: "台北松山",
    nmcStationCode: "VrMVF",
    nmcStationId: "58968",
    nmcPageUrl: "https://www.cwa.gov.tw/V8/C/W/County/County.html?CID=63",
    note: "改用台湾中央气象署官方台北市县市预报；若后面找到松山区级预报再继续下沉。",
  },
  // 亚洲国外城市（预报源：Open-Meteo，结算源：Wunderground 机场站）
  {
    citySlug: "tokyo",
    cityZh: "东京",
    cityEn: "Tokyo",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-tokyo",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-tokyo-on-june-17-2026",
    settlementStationName: "Tokyo Haneda Airport",
    settlementStationCode: "RJTT",
    forecastTarget: "东京羽田机场",
    latitude: 35.5494,
    longitude: 139.7798,
    timeZone: "Asia/Tokyo",
    note: "Open-Meteo 默认模型（含 JMA 数据），结算对标 Wunderground RJTT。",
  },
  {
    citySlug: "seoul",
    cityZh: "首尔",
    cityEn: "Seoul",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-seoul",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-seoul-on-june-17-2026",
    settlementStationName: "Seoul Gimpo International Airport",
    settlementStationCode: "RKSS",
    forecastTarget: "首尔金浦机场",
    latitude: 37.5583,
    longitude: 126.7903,
    timeZone: "Asia/Seoul",
    note: "Open-Meteo 默认模型，结算对标 Wunderground RKSS。",
  },
  {
    citySlug: "singapore",
    cityZh: "新加坡",
    cityEn: "Singapore",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-singapore",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-singapore-on-june-17-2026",
    settlementStationName: "Singapore Changi Airport",
    settlementStationCode: "WSSS",
    forecastTarget: "新加坡樟宜机场",
    latitude: 1.3644,
    longitude: 103.9915,
    timeZone: "Asia/Singapore",
    note: "Open-Meteo 默认模型，结算对标 Wunderground WSSS。",
  },
  {
    citySlug: "kuala-lumpur",
    cityZh: "吉隆坡",
    cityEn: "Kuala Lumpur",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-kuala-lumpur",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-kuala-lumpur-on-june-17-2026",
    settlementStationName: "Kuala Lumpur International Airport",
    settlementStationCode: "WMKK",
    forecastTarget: "吉隆坡国际机场",
    latitude: 2.7456,
    longitude: 101.7099,
    timeZone: "Asia/Kuala_Lumpur",
    note: "Open-Meteo 默认模型，结算对标 Wunderground WMKK。",
  },
  {
    citySlug: "manila",
    cityZh: "马尼拉",
    cityEn: "Manila",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-manila",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-manila-on-june-17-2026",
    settlementStationName: "Manila Ninoy Aquino International Airport",
    settlementStationCode: "RPLL",
    forecastTarget: "马尼拉尼诺伊机场",
    latitude: 14.5086,
    longitude: 121.0194,
    timeZone: "Asia/Manila",
    note: "Open-Meteo 默认模型，结算对标 Wunderground RPLL。",
  },
  // ========== 欧洲城市（预报源：Open-Meteo，结算源：Wunderground 机场站） ==========
  {
    citySlug: "london",
    cityZh: "伦敦",
    cityEn: "London",
    region: "europe",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-london",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-london-on-june-17-2026",
    settlementStationName: "London City Airport",
    settlementStationCode: "EGLC",
    forecastTarget: "伦敦城市机场",
    latitude: 51.5074,
    longitude: -0.1278,
    timeZone: "Europe/London",
    note: "Open-Meteo 默认模型（含 UK Met Office），结算对标 Wunderground EGLC。",
  },
  {
    citySlug: "paris",
    cityZh: "巴黎",
    cityEn: "Paris",
    region: "europe",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-paris",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-paris-on-june-17-2026",
    settlementStationName: "Paris Le Bourget Airport",
    settlementStationCode: "LFPB",
    forecastTarget: "巴黎勒布尔歇机场",
    latitude: 48.8566,
    longitude: 2.3522,
    timeZone: "Europe/Paris",
    note: "Open-Meteo 默认模型（含 Météo-France），结算对标 Wunderground LFPB。",
  },
  {
    citySlug: "madrid",
    cityZh: "马德里",
    cityEn: "Madrid",
    region: "europe",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-madrid",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-madrid-on-june-17-2026",
    settlementStationName: "Madrid Barajas Airport",
    settlementStationCode: "LEMD",
    forecastTarget: "马德里巴拉哈斯机场",
    latitude: 40.4168,
    longitude: -3.7038,
    timeZone: "Europe/Madrid",
    note: "Open-Meteo 默认模型，结算对标 Wunderground LEMD。",
  },
  {
    citySlug: "helsinki",
    cityZh: "赫尔辛基",
    cityEn: "Helsinki",
    region: "europe",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-helsinki",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-helsinki-on-june-17-2026",
    settlementStationName: "Helsinki Vantaa Airport",
    settlementStationCode: "EFHK",
    forecastTarget: "赫尔辛基万塔机场",
    latitude: 60.1699,
    longitude: 24.9384,
    timeZone: "Europe/Helsinki",
    note: "Open-Meteo 默认模型（含 MET Norway），结算对标 Wunderground EFHK。",
  },
  // ========== 北美城市（预报源：Open-Meteo，结算源：Wunderground/NWS 机场站） ==========
  {
    citySlug: "new-york",
    cityZh: "纽约",
    cityEn: "New York",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-nyc",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-nyc-on-june-17-2026",
    settlementStationName: "New York Central Park",
    settlementStationCode: "KNYC",
    forecastTarget: "纽约中央公园",
    latitude: 40.7128,
    longitude: -74.006,
    timeZone: "America/New_York",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型（含 NCEP GFS/HRRR），结算对标 NWS CLI KNYC。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "los-angeles",
    cityZh: "洛杉矶",
    cityEn: "Los Angeles",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-los-angeles",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-los-angeles-on-june-17-2026",
    settlementStationName: "Los Angeles International Airport",
    settlementStationCode: "KLAX",
    forecastTarget: "洛杉矶国际机场",
    latitude: 34.0522,
    longitude: -118.2437,
    timeZone: "America/Los_Angeles",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KLAX。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "chicago",
    cityZh: "芝加哥",
    cityEn: "Chicago",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-chicago",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-chicago-on-june-17-2026",
    settlementStationName: "Chicago Midway Airport",
    settlementStationCode: "KMDW",
    forecastTarget: "芝加哥中途机场",
    latitude: 41.8781,
    longitude: -87.6298,
    timeZone: "America/Chicago",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KMDW。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "toronto",
    cityZh: "多伦多",
    cityEn: "Toronto",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-toronto",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-toronto-on-june-17-2026",
    settlementStationName: "Toronto Pearson International Airport",
    settlementStationCode: "CYYZ",
    forecastTarget: "多伦多皮尔逊机场",
    latitude: 43.6532,
    longitude: -79.3832,
    timeZone: "America/Toronto",
    note: "Open-Meteo 默认模型（含 GEM），结算对标 Wunderground CYYZ。",
  },
  {
    citySlug: "miami",
    cityZh: "迈阿密",
    cityEn: "Miami",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-miami",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-miami-on-june-17-2026",
    settlementStationName: "Miami International Airport",
    settlementStationCode: "KMIA",
    forecastTarget: "迈阿密国际机场",
    latitude: 25.7617,
    longitude: -80.1918,
    timeZone: "America/New_York",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KMIA。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "san-francisco",
    cityZh: "旧金山",
    cityEn: "San Francisco",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-san-francisco",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-san-francisco-on-june-17-2026",
    settlementStationName: "San Francisco International Airport",
    settlementStationCode: "KSFO",
    forecastTarget: "旧金山国际机场",
    latitude: 37.7749,
    longitude: -122.4194,
    timeZone: "America/Los_Angeles",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KSFO。Polymarket 用华氏，forecast 同步用华氏。",
  },
  // ========== 国内城市补充（预报源：nmc，结算源：Wunderground 机场站） ==========
  {
    citySlug: "qingdao",
    cityZh: "青岛",
    cityEn: "Qingdao",
    region: "domestic",
    eventBaseSlug: "highest-temperature-in-qingdao",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-qingdao-on-june-17-2026",
    settlementStationName: "Qingdao Jiaodong International Airport",
    settlementStationCode: "ZSQD",
    forecastTarget: "青岛胶州市",
    nmcStationCode: "QZdFI",
    nmcStationId: "54849",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/ASD/jiaozhou.html",
    latitude: 36.3661,
    longitude: 120.3826,
    timeZone: "Asia/Shanghai",
    note: "国内城市，预报源 nmc（中央气象局）胶州站，结算对标 Wunderground ZSQD（胶东国际机场）。",
  },
  // ========== 亚洲国外城市补充（预报源：Open-Meteo，结算源：Wunderground 机场站） ==========
  {
    citySlug: "busan",
    cityZh: "釜山",
    cityEn: "Busan",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-busan",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-busan-on-june-17-2026",
    settlementStationName: "Busan Gimhae Airport",
    settlementStationCode: "RKPK",
    forecastTarget: "釜山金海机场",
    latitude: 35.1796,
    longitude: 129.0756,
    timeZone: "Asia/Seoul",
    note: "Open-Meteo 默认模型，结算对标 Wunderground RKPK。",
  },
  {
    citySlug: "karachi",
    cityZh: "卡拉奇",
    cityEn: "Karachi",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-karachi",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-karachi-on-june-17-2026",
    settlementStationName: "Karachi Jinnah Airport",
    settlementStationCode: "OPKC",
    forecastTarget: "卡拉奇真纳机场",
    latitude: 24.8607,
    longitude: 67.0011,
    timeZone: "Asia/Karachi",
    note: "Open-Meteo 默认模型，结算对标 Wunderground OPKC。",
  },
  {
    citySlug: "lucknow",
    cityZh: "勒克瑙",
    cityEn: "Lucknow",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-lucknow",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-lucknow-on-june-17-2026",
    settlementStationName: "Lucknow Airport",
    settlementStationCode: "VILK",
    forecastTarget: "勒克瑙机场",
    latitude: 26.8467,
    longitude: 80.9462,
    timeZone: "Asia/Kolkata",
    note: "Open-Meteo 默认模型，结算对标 Wunderground VILK。",
  },
  {
    citySlug: "jeddah",
    cityZh: "吉达",
    cityEn: "Jeddah",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-jeddah",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-jeddah-on-june-17-2026",
    settlementStationName: "Jeddah King Abdulaziz Airport",
    settlementStationCode: "OEJN",
    forecastTarget: "吉达阿卜杜勒-阿齐兹机场",
    latitude: 21.4858,
    longitude: 39.1925,
    timeZone: "Asia/Riyadh",
    note: "Open-Meteo 默认模型，结算对标 Wunderground OEJN。",
  },
  {
    citySlug: "tel-aviv",
    cityZh: "特拉维夫",
    cityEn: "Tel Aviv",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-tel-aviv",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-tel-aviv-on-june-17-2026",
    settlementStationName: "Tel Aviv Ben Gurion Airport",
    settlementStationCode: "LLBG",
    forecastTarget: "特拉维夫本古里安机场",
    latitude: 32.0853,
    longitude: 34.7818,
    timeZone: "Asia/Jerusalem",
    note: "Open-Meteo 默认模型，结算对标 Wunderground LLBG。",
  },
  {
    citySlug: "ankara",
    cityZh: "安卡拉",
    cityEn: "Ankara",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-ankara",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-ankara-on-june-17-2026",
    settlementStationName: "Ankara Esenboga Airport",
    settlementStationCode: "LTAC",
    forecastTarget: "安卡拉埃森博加机场",
    latitude: 39.9334,
    longitude: 32.8597,
    timeZone: "Europe/Istanbul",
    note: "Open-Meteo 默认模型，结算对标 Wunderground LTAC。",
  },
  {
    citySlug: "istanbul",
    cityZh: "伊斯坦布尔",
    cityEn: "Istanbul",
    region: "asia-foreign",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-istanbul",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-istanbul-on-june-17-2026",
    settlementStationName: "Istanbul Airport",
    settlementStationCode: "LTFM",
    forecastTarget: "伊斯坦布尔机场",
    latitude: 41.0082,
    longitude: 28.9784,
    timeZone: "Europe/Istanbul",
    note: "Open-Meteo 默认模型，结算对标 Wunderground LTFM。",
  },
  // ========== 欧洲城市补充（预报源：Open-Meteo，结算源：Wunderground 机场站） ==========
  {
    citySlug: "milan",
    cityZh: "米兰",
    cityEn: "Milan",
    region: "europe",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-milan",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-milan-on-june-17-2026",
    settlementStationName: "Milan Linate Airport",
    settlementStationCode: "LIMC",
    forecastTarget: "米兰利纳特机场",
    latitude: 45.4642,
    longitude: 9.19,
    timeZone: "Europe/Rome",
    note: "Open-Meteo 默认模型（含 ItaliaMeteo），结算对标 Wunderground LIMC。",
  },
  {
    citySlug: "munich",
    cityZh: "慕尼黑",
    cityEn: "Munich",
    region: "europe",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-munich",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-munich-on-june-17-2026",
    settlementStationName: "Munich Airport",
    settlementStationCode: "EDDM",
    forecastTarget: "慕尼黑机场",
    latitude: 48.1351,
    longitude: 11.582,
    timeZone: "Europe/Berlin",
    note: "Open-Meteo 默认模型（含 DWD ICON），结算对标 Wunderground EDDM。",
  },
  {
    citySlug: "warsaw",
    cityZh: "华沙",
    cityEn: "Warsaw",
    region: "europe",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-warsaw",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-warsaw-on-june-17-2026",
    settlementStationName: "Warsaw Chopin Airport",
    settlementStationCode: "EPWA",
    forecastTarget: "华沙肖邦机场",
    latitude: 52.2297,
    longitude: 21.0122,
    timeZone: "Europe/Warsaw",
    note: "Open-Meteo 默认模型，结算对标 Wunderground EPWA。",
  },
  {
    citySlug: "moscow",
    cityZh: "莫斯科",
    cityEn: "Moscow",
    region: "europe",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-moscow",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-moscow-on-june-17-2026",
    settlementStationName: "Moscow Domodedovo Airport",
    settlementStationCode: "UUDD",
    forecastTarget: "莫斯科多莫杰多沃机场",
    latitude: 55.7558,
    longitude: 37.6173,
    timeZone: "Europe/Moscow",
    note: "Open-Meteo 默认模型，结算对标 Wunderground UUDD。",
  },
  {
    citySlug: "amsterdam",
    cityZh: "阿姆斯特丹",
    cityEn: "Amsterdam",
    region: "europe",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-amsterdam",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-amsterdam-on-june-17-2026",
    settlementStationName: "Amsterdam Schiphol Airport",
    settlementStationCode: "EHAM",
    forecastTarget: "阿姆斯特丹史基浦机场",
    latitude: 52.3676,
    longitude: 4.9041,
    timeZone: "Europe/Amsterdam",
    note: "Open-Meteo 默认模型（含 KNMI），结算对标 Wunderground EHAM。",
  },
  // ========== 北美城市补充（预报源：Open-Meteo，结算源：Wunderground/NWS 机场站） ==========
  {
    citySlug: "atlanta",
    cityZh: "亚特兰大",
    cityEn: "Atlanta",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-atlanta",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-atlanta-on-june-17-2026",
    settlementStationName: "Atlanta Hartsfield Airport",
    settlementStationCode: "KATL",
    forecastTarget: "亚特兰大哈茨菲尔德机场",
    latitude: 33.749,
    longitude: -84.388,
    timeZone: "America/New_York",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KATL。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "austin",
    cityZh: "奥斯汀",
    cityEn: "Austin",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-austin",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-austin-on-june-17-2026",
    settlementStationName: "Austin Bergstrom Airport",
    settlementStationCode: "KAUS",
    forecastTarget: "奥斯汀伯格斯特罗姆机场",
    latitude: 30.2672,
    longitude: -97.7431,
    timeZone: "America/Chicago",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KAUS。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "dallas",
    cityZh: "达拉斯",
    cityEn: "Dallas",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-dallas",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-dallas-on-june-17-2026",
    settlementStationName: "Dallas Love Field Airport",
    settlementStationCode: "KDAL",
    forecastTarget: "达拉斯爱田机场",
    latitude: 32.7767,
    longitude: -96.797,
    timeZone: "America/Chicago",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KDAL。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "houston",
    cityZh: "休斯顿",
    cityEn: "Houston",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-houston",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-houston-on-june-17-2026",
    settlementStationName: "Houston Hobby Airport",
    settlementStationCode: "KHOU",
    forecastTarget: "休斯顿霍比机场",
    latitude: 29.7604,
    longitude: -95.3698,
    timeZone: "America/Chicago",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KHOU。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "denver",
    cityZh: "丹佛",
    cityEn: "Denver",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-denver",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-denver-on-june-17-2026",
    settlementStationName: "Denver International Airport",
    settlementStationCode: "KDEN",
    forecastTarget: "丹佛国际机场",
    latitude: 39.7392,
    longitude: -104.9903,
    timeZone: "America/Denver",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KDEN。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "seattle",
    cityZh: "西雅图",
    cityEn: "Seattle",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-seattle",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-seattle-on-june-17-2026",
    settlementStationName: "Seattle Tacoma Airport",
    settlementStationCode: "KSEA",
    forecastTarget: "西雅图塔科马机场",
    latitude: 47.6062,
    longitude: -122.3321,
    timeZone: "America/Los_Angeles",
    unit: "fahrenheit",
    note: "Open-Meteo 默认模型，结算对标 Wunderground KSEA。Polymarket 用华氏，forecast 同步用华氏。",
  },
  {
    citySlug: "mexico-city",
    cityZh: "墨西哥城",
    cityEn: "Mexico City",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-mexico-city",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-mexico-city-on-june-17-2026",
    settlementStationName: "Mexico City International Airport",
    settlementStationCode: "MMMX",
    forecastTarget: "墨西哥城国际机场",
    latitude: 19.4326,
    longitude: -99.1332,
    timeZone: "America/Mexico_City",
    note: "Open-Meteo 默认模型，结算对标 Wunderground MMMX。",
  },
  {
    citySlug: "panama-city",
    cityZh: "巴拿马城",
    cityEn: "Panama City",
    region: "north-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-panama-city",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-panama-city-on-june-17-2026",
    settlementStationName: "Panama City Tocumen Airport",
    settlementStationCode: "MPTO",
    forecastTarget: "巴拿马城托库门机场",
    latitude: 8.9824,
    longitude: -79.5199,
    timeZone: "America/Panama",
    note: "Open-Meteo 默认模型，结算对标 Wunderground MPTO。",
  },
  // ========== 南美城市（预报源：Open-Meteo，结算源：Wunderground 机场站） ==========
  {
    citySlug: "buenos-aires",
    cityZh: "布宜诺斯艾利斯",
    cityEn: "Buenos Aires",
    region: "south-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-buenos-aires",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-buenos-aires-on-june-17-2026",
    settlementStationName: "Buenos Aires Ezeiza Airport",
    settlementStationCode: "SAEZ",
    forecastTarget: "布宜诺斯艾利斯埃塞萨机场",
    latitude: -34.6037,
    longitude: -58.3816,
    timeZone: "America/Argentina/Buenos_Aires",
    note: "Open-Meteo 默认模型，结算对标 Wunderground SAEZ。",
  },
  {
    citySlug: "sao-paulo",
    cityZh: "圣保罗",
    cityEn: "Sao Paulo",
    region: "south-america",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-sao-paulo",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-sao-paulo-on-june-17-2026",
    settlementStationName: "Sao Paulo Congonhas Airport",
    settlementStationCode: "SBSP",
    forecastTarget: "圣保罗孔戈尼亚斯机场",
    latitude: -23.5505,
    longitude: -46.6333,
    timeZone: "America/Sao_Paulo",
    note: "Open-Meteo 默认模型，结算对标 Wunderground SBSP。",
  },
  // ========== 非洲城市（预报源：Open-Meteo，结算源：Wunderground 机场站） ==========
  {
    citySlug: "cape-town",
    cityZh: "开普敦",
    cityEn: "Cape Town",
    region: "africa",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-cape-town",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-cape-town-on-june-17-2026",
    settlementStationName: "Cape Town International Airport",
    settlementStationCode: "FACT",
    forecastTarget: "开普敦国际机场",
    latitude: -33.9249,
    longitude: 18.4241,
    timeZone: "Africa/Johannesburg",
    note: "Open-Meteo 默认模型，结算对标 Wunderground FACT。",
  },
  // ========== 大洋洲城市（预报源：Open-Meteo，结算源：Wunderground 机场站） ==========
  {
    citySlug: "wellington",
    cityZh: "惠灵顿",
    cityEn: "Wellington",
    region: "oceania",
    forecastSource: "open-meteo",
    eventBaseSlug: "highest-temperature-in-wellington",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-wellington-on-june-17-2026",
    settlementStationName: "Wellington Airport",
    settlementStationCode: "NZWN",
    forecastTarget: "惠灵顿机场",
    latitude: -41.2865,
    longitude: 174.7762,
    timeZone: "Pacific/Auckland",
    note: "Open-Meteo 默认模型（含 MetService），结算对标 Wunderground NZWN。",
  },
];

const ACTIVE_WEATHER_CITY_SLUGS = new Set([
  "beijing",
  "shanghai",
  "guangzhou",
  "shenzhen",
  "wuhan",
  "chengdu",
  "chongqing",
  "hong-kong",
  "taipei",
  "tokyo",
  "seoul",
  "singapore",
  "kuala-lumpur",
  "manila",
  "london",
  "paris",
  "madrid",
  "helsinki",
  "new-york",
  "los-angeles",
  "chicago",
  "toronto",
  "miami",
  "san-francisco",
  "qingdao",
  "busan",
  "karachi",
  "lucknow",
  "jeddah",
  "tel-aviv",
  "ankara",
  "istanbul",
  "milan",
  "munich",
  "warsaw",
  "moscow",
  "amsterdam",
  "atlanta",
  "austin",
  "dallas",
  "houston",
  "denver",
  "seattle",
  "mexico-city",
  "panama-city",
  "buenos-aires",
  "sao-paulo",
  "cape-town",
  "wellington",
]);

export const WEATHER_CITY_CONFIGS = ALL_WEATHER_CITY_CONFIGS.filter((item) =>
  ACTIVE_WEATHER_CITY_SLUGS.has(item.citySlug),
);

export function getWeatherMarketCounts() {
  return {
    trackedCities: WEATHER_CITY_CONFIGS.length,
  };
}

// 所有城市统一北京时间 00:10 下单（不再按当地时区换算）
export function getOrderTimeBeijing(config) {
  return "00:10";
}
