const ALL_WEATHER_CITY_CONFIGS = [
  {
    citySlug: "beijing",
    cityZh: "北京",
    cityEn: "Beijing",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-beijing",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-beijing-on-april-16-2026",
    settlementStationName: "Beijing Capital International Airport",
    settlementStationCode: "ZBAA",
    forecastTarget: "北京顺义区",
    forecastBackupTarget: "北京朝阳区",
    nmcStationCode: "MKoqG",
    nmcStationId: "54398",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/ABJ/shunyi.html",
    note: "按顺义页抓取，朝阳仅作辅助对照。",
  },
  {
    citySlug: "shanghai",
    cityZh: "上海",
    cityEn: "Shanghai",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-shanghai",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-shanghai-on-april-16-2026",
    settlementStationName: "Shanghai Pudong International Airport",
    settlementStationCode: "ZSPD",
    forecastTarget: "上海浦东新区",
    forecastBackupTarget: null,
    nmcStationCode: "atcMf",
    nmcStationId: "58370",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/ASH/pudong.html",
    note: "直接按浦东页抓取。",
  },
  {
    citySlug: "guangzhou",
    cityZh: "广州",
    cityEn: "Guangzhou",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-guangzhou",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-guangzhou-on-april-16-2026",
    settlementStationName: "Guangzhou Baiyun International Airport",
    settlementStationCode: "ZGGG",
    forecastTarget: "广州花都区",
    forecastBackupTarget: "广州白云区",
    nmcStationCode: "DFILe",
    nmcStationId: "59284",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/AGD/huadu.html",
    note: "白云机场优先按花都页抓取。",
  },
  {
    citySlug: "shenzhen",
    cityZh: "深圳",
    cityEn: "Shenzhen",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-shenzhen",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-shenzhen-on-april-16-2026",
    settlementStationName: "Shenzhen Bao'an International Airport",
    settlementStationCode: "ZGSZ",
    forecastTarget: "深圳市",
    forecastBackupTarget: "深圳宝安区",
    nmcStationCode: "AhpEU",
    nmcStationId: "59493",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/AGD/shenzuo.html",
    note: "中央台当前没有单独宝安页，先用深圳城市页。",
  },
  {
    citySlug: "wuhan",
    cityZh: "武汉",
    cityEn: "Wuhan",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-wuhan",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-wuhan-on-april-16-2026",
    settlementStationName: "Wuhan Tianhe International Airport",
    settlementStationCode: "ZHHH",
    forecastTarget: "武汉市",
    forecastBackupTarget: "武汉黄陂区",
    nmcStationCode: "bSpCz",
    nmcStationId: "57494",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/AHB/wuhan.html",
    note: "中央台当前没有黄陂独立页，先用武汉城市页。",
  },
  {
    citySlug: "chengdu",
    cityZh: "成都",
    cityEn: "Chengdu",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-chengdu",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-chengdu-on-april-16-2026",
    settlementStationName: "Chengdu Shuangliu International Airport",
    settlementStationCode: "ZUUU",
    forecastTarget: "成都双流区",
    forecastBackupTarget: null,
    nmcStationCode: "grFhZ",
    nmcStationId: "56288",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/ASC/shuangliu.html",
    note: "直接按双流页抓取。",
  },
  {
    citySlug: "chongqing",
    cityZh: "重庆",
    cityEn: "Chongqing",
    forecastSource: "nmc",
    eventBaseSlug: "highest-temperature-in-chongqing",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-chongqing-on-april-16-2026",
    settlementStationName: "Chongqing Jiangbei International Airport",
    settlementStationCode: "ZUCK",
    forecastTarget: "重庆渝北区",
    forecastBackupTarget: null,
    nmcStationCode: "xFVYU",
    nmcStationId: "57513",
    nmcPageUrl: "https://www.nmc.cn/publish/forecast/ACQ/yubei.html",
    note: "直接按渝北页抓取。",
  },
  {
    citySlug: "hong-kong",
    cityZh: "香港",
    cityEn: "Hong Kong",
    forecastSource: "hko-fnd",
    eventBaseSlug: "highest-temperature-in-hong-kong",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-hong-kong-on-april-16-2026",
    settlementStationName: "Hong Kong Observatory",
    settlementStationCode: null,
    forecastTarget: "香港天文台",
    forecastBackupTarget: "香港",
    nmcStationCode: "hcBhy",
    nmcStationId: "45005",
    nmcPageUrl: "https://data.weather.gov.hk/weatherAPI/opendata/weather.php?dataType=fnd&lang=en",
    note: "改用香港天文台官方 9-day forecast open data。",
  },
  {
    citySlug: "taipei",
    cityZh: "台北",
    cityEn: "Taipei",
    forecastSource: "cwa-county-63",
    eventBaseSlug: "highest-temperature-in-taipei",
    eventUrl: "https://polymarket.com/zh/event/highest-temperature-in-taipei-on-april-16-2026",
    settlementStationName: "Taipei Songshan Airport Station",
    settlementStationCode: "RCSS",
    forecastTarget: "台北市",
    forecastBackupTarget: "台北松山",
    nmcStationCode: "VrMVF",
    nmcStationId: "58968",
    nmcPageUrl: "https://www.cwa.gov.tw/V8/C/W/County/County.html?CID=63",
    note: "改用台湾中央气象署官方台北市县市预报；若后面找到松山区级预报再继续下沉。",
  },
];

const ACTIVE_WEATHER_CITY_SLUGS = new Set([
  "beijing",
  "shanghai",
  "guangzhou",
  "shenzhen",
  "wuhan",
  "chengdu",
  "chongqing",
  "hong-kong",
  "taipei",
]);

export const WEATHER_CITY_CONFIGS = ALL_WEATHER_CITY_CONFIGS.filter((item) =>
  ACTIVE_WEATHER_CITY_SLUGS.has(item.citySlug),
);

export function getWeatherMarketCounts() {
  return {
    trackedCities: WEATHER_CITY_CONFIGS.length,
  };
}
